### ISSUE TITLE
Request for equianglar CT revision

### ISSUE THREAD

**Issue by Parker-xia** [DIDSR/MCGPU#8]
Dear author:

I am currently working on a project that involves the simulation of equianglar CT. I wanted to know where your code can be revised for the situation.

Thanks a lot.

**Comment by andreubs** [comment]
Hi Parker-Xia,

I have never tried to simulate any CT geometry with variable source-to-detector distance, but it can be definitely simulated with Monte Carlo. However, to simulate it with MCGPU you will need to edit the source code, because the default version expects a standard CBCT geometry with a constant sdd. 

To model your equiangular CT geometry, you will need to modify the [set_CT_trajectory](https://github.com/DIDSR/MCGPU/blob/8796dd044e65fce31af23ea0dd6840a1f4e3d261/MC-GPU_v1.3.cu#L3238C6-L3238C23) function in file MC-GPU_v1.3.cu. There you can change the position and field-of-view (collimation) of the source at each projection (source_data array), and also the detector parameters and sdd at each projection (detector_data array). 

By the way, are you the author of the recent paper in Medical Physics on Generalized-equiangular geometry CT?

I hope the software is useful.

Best regards,

     Andreu
